name: schoolapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  show_up_animation: ^1.0.2
  provider: ^4.3.2+2
  cached_network_image: ^2.3.2+1
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.2
  url_launcher: ^5.4.11
  rating_bar: ^0.2.0
  flutter_zoom_drawer: ^1.0.4
  fluttertoast: ^7.1.1
  device_apps: ^1.2.0
  http: ^0.12.2
  firebase_storage: ^4.0.0
  agora_rtc_engine: ^3.1.3
  permission_handler: ^3.0.0
  image_picker: ^0.6.6+4
  share: ^0.6.5+4


dev_dependencies:
  flutter_test:
    sdk: flutter
#  git: git://github.com/admarwick/flutter_screen_recording.git

flutter:
 
  uses-material-design: true

  assets:
   - assets/logo.png

  fonts: 
     - family: Ptsans
       fonts:
         - asset: font/PTSans-Regular.ttf
     - family: Nunito
       fonts:
         - asset: font/Nunito-Regular.ttf
     - family: QuickBold
       fonts:
         - asset: font/Quicksand-bold.ttf
     - family: Quick
       fonts:
         - asset: font/Quicksand-VariableFont_wght.ttf
     - family: Fred
       fonts:
         - asset: font/FredokaOne-Regular.ttf